### ISSUE TITLE
Possible to Add Moreores Support to this Add On?

### ISSUE THREAD

**Issue by FriendlyGamer** [louisroyer/minetest-toolranks-extras#1]
So that moreores' tools, swords or what not works with ToolRanks as well as the hoes this add on provides?

**Comment by louisroyer** [comment]
Moreores fully supports ToolRanks since https://github.com/minetest-mods/moreores/commit/3c44a9be585ef7bf093bf3803f877baadef47415, but no release has been tagged since, so if you have installed moreores via contentdb, consider using [the current master archive](https://github.com/minetest-mods/moreores/archive/master.zip) instead.

**Comment by FriendlyGamer** [comment]
Awesome, thanks very much for being such a helpful person to me I really appreciate it. :)
